### ISSUE TITLE
I get the error: "Receiver not registered"

### ISSUE THREAD

**Issue by toxoz41** [tlgbltcn/BluetoothHelper#1]
Related error is attached. ![error](https://user-images.githubusercontent.com/26853131/74937966-32f5f580-53fe-11ea-9281-99b737783a27.png)
**The temporary solution is to remove the "context.unregisterReceiver (mBluetoothDeviceFounderReceiver)" line in the onFinishDiscovering method in the BluetoothHelper class.**

**Comment by tlgbltcn** [comment]
Hi toxoz41,

Could you try again?

**Comment by AzimLord** [comment]
@tlgbltcn Still happening

**Comment by glebkravchenko** [comment]
Yep, have same issue

**Comment by glebkravchenko** [comment]
@tlgbltcn  please approve #3
